name = "prismplay/autopublish_template"
version = "0.1.0"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dependencies]
scripts = { name = "jiwonz/pesde_scripts_rojo", version = "^0.1.0-rc.1", target = "lune" }
signal = { wally = "sleitnick/signal", version = "^2.0.3" }
knit = { wally = "sleitnick/knit", version = "^1.7.0" }
trove = { wally = "sleitnick/trove", version = "^1.5.1" }
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0-rc.7", target = "lune" }
simplepath = { wally = "jessekroeske/simplepath", version = "^2.2.2" }
