owner:
  group: 35058813 

state:
  remote:
    region: eu-north-1
    bucket: r0rnor-mantle-states
    key: days-to-lose-weight

environments:
  - label: prod
    branches:
      - main
    targetAccess: public

target:
  experience:
    icon: marketing/DefaultIcon.png
    thumbnails:
      - marketing/MainThumbnail.png
      - marketing/SecondThumbnail.png
    configuration:
      playableDevices: [computer, console, phone, tablet]
      privateServers:
        price: 75
      enableStudioAccessToApis: true
      avatarType: r15
      avatarAnimationType: playerChoice
    spatialVoice:
      enabled: true
    places:
      start:
        file: Lobby.rbxlx
        configuration:
          name: 24 Days to lose weight
          description: |-
            You are locked in summer camp.
            Lose weight before the end or coach gets mad!
            Goodluck!


            --------------------------------------------------------------------------
            Brought to you by PrismPlays ❤️

            Report bugs in the community server below!
            ⭐️👍Like and favourite the game if you enjoy it!
          maxPlayerCount: 50
          allowCopying: false
      mainGame:
        file: MainGame.rbxlx
        configuration:
          name: 24 Days to lose weight - Main Game
          description: you only have 24^2 hours to lose weight
          maxPlayerCount: 4
          allowCopying: false
    products:
    passes: