[assets]
config_path = "asphalt.toml"
lock_path = "asphalt_locks_files/%s.toml"

[env]
MANTLE_AWS_ACCESS_KEY_ID = "AKIA35J7HFQBK4RXMLGB"
MANTLE_AWS_SECRET_ACCESS_KEY = "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"

[executor]
shell = true
stdio = "default"

[groups.dev]
apiKey = "mHNvfe4BGkq1rn23r1W/YUU178HWAIR9vHeDItkCInEfOYgEZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluTnBaeTB5TURJeExUQTNMVEV6VkRFNE9qVXhPalE1V2lJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaVlYTmxRWEJwUzJWNUlqb2liVWhPZG1abE5FSkhhM0V4Y200eU0zSXhWeTlaVlZVeE56aElWMEZKVWpsMlNHVkVTWFJyUTBsdVJXWlBXV2RGSWl3aWIzZHVaWEpKWkNJNklqTTFPRE0wTWpreUlpd2lZWFZrSWpvaVVtOWliRzk0U1c1MFpYSnVZV3dpTENKcGMzTWlPaUpEYkc5MVpFRjFkR2hsYm5ScFkyRjBhVzl1VTJWeWRtbGpaU0lzSW1WNGNDSTZNVGMwT1RVME5ERTFPU3dpYVdGMElqb3hOelE1TlRRd05UVTVMQ0p1WW1ZaU9qRTNORGsxTkRBMU5UbDkuTGgxZU01UWJ3cGRqNXF2eDJlamdqZTkzaTBRNndKY1AxWVNGLVRHUTMzR1RwaS1HTVJ3M01BY0dBTmFtdlZGcjk4eHB3SlhUM3FyWHVFY2NxbTFuamRWZFlqbzBZT2JRclA3WUJSS3JWVTN4MmZXb3lPRGZWdmJmaGFWSTY2YlAyMU9pNU85LXp3TXJxcjd3Mk1BbXZaLWVqM0V2UU1iMmphQV9lVE9Lbkk2b0RBQWhzTHZIVEZmc0xSXzlhT095TjRvRG95Y1BGM2JyR2R5cmtfdmJGdU9HMzN0ZHRUeXRYOHN6eXNnMGlXR3ZHMEp2OFhBc2lscUhEMlJRVVV0VWtGLUw2X2VnM2NMLTR1ckhUVk5pX01fdzNsTlpncWFGYjc3UWNIaGV1NTM4N0xoMktDY2NJNTlLM0lMWE5wMWtJZU16ZmlqVUtrOXUxWVp1LUhJaVlR"
id = 35834292

[groups.feature]
apiKey = "Kx+qIvtgT0G77mJAgO82ptqa0aT9v3wzdyGvrp3uz+TFPHRGZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluTnBaeTB5TURJeExUQTNMVEV6VkRFNE9qVXhPalE1V2lJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaVlYTmxRWEJwUzJWNUlqb2lTM2dyY1VsMmRHZFVNRWMzTjIxS1FXZFBPREp3ZEhGaE1HRlVPWFl6ZDNwa2VVZDJjbkF6ZFhvclZFWlFTRkpISWl3aWIzZHVaWEpKWkNJNklqTTFNalF6TnpRM0lpd2lZWFZrSWpvaVVtOWliRzk0U1c1MFpYSnVZV3dpTENKcGMzTWlPaUpEYkc5MVpFRjFkR2hsYm5ScFkyRjBhVzl1VTJWeWRtbGpaU0lzSW1WNGNDSTZNVGMwT1RZeU9EYzROQ3dpYVdGMElqb3hOelE1TmpJMU1UZzBMQ0p1WW1ZaU9qRTNORGsyTWpVeE9EUjkuWmN2QmNidUp1UXBRVE1CcGlTdzcyY0QtRngxcVVoa2pyYVRORnRmM1JTaFVBcVNRRDJwM1M1QkJ3dDFxOG1QUkw2anhwME91V2VQc3hMTG5fVmlXZWdDeDVJVXNlZjRCR1poeEZhYUxsbFNpYnJiT0tDWjhQWEQ3aWZvZW5pa0hRZXpFUXo0TTJYMHhkVGlnXzB3UG1VdW1xa08wWFpnZWo5X0hwMnF6YTFMaVFmblBmVTd1R2d6RkQxbDlObGd0MlNuQk0yQWpzeVc5SmlremtwODNNaVZQRzdsclo5b1lmU1ZpTGZqdjd5MGNFSjFNSk1aUF9oalMxbFhpWDl2bVZDSHlIRlJVQThCeE8tYTFlYTV2dWRydDM4S3A3OEFrRFljd3YweHhyNF9acjlnR0UwV0ROYmtmc3FCejhoa0ZKemZ4MENNT3RrbFBXMEhGVVBzWmZR"
id = 35243747

[groups.prod]
apiKey = "18XLqVmoTEGYmrqlzPeNR/5vgmIlIVsI8hxdPWurbbR6KXIKZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkluTnBaeTB5TURJeExUQTNMVEV6VkRFNE9qVXhPalE1V2lJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaVlYTmxRWEJwUzJWNUlqb2lNVGhZVEhGV2JXOVVSVWRaYlhKeGJIcFFaVTVTTHpWMloyMUpiRWxXYzBrNGFIaGtVRmQxY21KaVVqWkxXRWxMSWl3aWIzZHVaWEpKWkNJNklqTTJNRGN5TkRrNElpd2lZWFZrSWpvaVVtOWliRzk0U1c1MFpYSnVZV3dpTENKcGMzTWlPaUpEYkc5MVpFRjFkR2hsYm5ScFkyRjBhVzl1VTJWeWRtbGpaU0lzSW1WNGNDSTZNVGMxTWpjNU5qRTFPQ3dpYVdGMElqb3hOelV5TnpreU5UVTRMQ0p1WW1ZaU9qRTNOVEkzT1RJMU5UaDkuRDdOcGtwVlJVeE03Qi1tb1hVbk9ZbnlaQ0hoZDdrNGpDa3pMT1hBTmtrdWhaRm8wM1ZhYTZSYnA3TFFETXNtY05wclJiZ28wV1BnbEp3VFhuUzl0dkZ2ZXlSRTVJR2RuaU8wNG5nVGdTM1dPRkQtSi1McUNlUEhxNWNDclVtWTFUTGdnekxGdGVBLVdZRHVGMFduT2pocVJBbk9GMzhDQ1o5RHJzaGdERlhKOGx3Z3FQMzBwU3VjZTR6VWhOZjBlYWNoSXZpdzF4dW5TVU9WbEZyc1pCQVRzSVlVM05PQVlwUnhSaEd3QXFIRzV6NFc3ajNTaFJwLXdsYWhITkpLTmtRRko1UXk5Tlc5aTFNOTZSYm5LX04tOThLb2FYZ0lxM21SSTQ0ZWNyX2d3d1pkb3UwSHY4a2NCblk0TS1iRlJRbEVIcU13S3lKc2NoQzJSRHM4cFhR"
id = 36072498

[mantle]
marketing_out_path = "ReplicatedStorage/Marketing.luau"

[multiplace]
current_place = "Lobby"
places = [
    "MainGame",
    "Lobby",
]

[structure]
game = "%s.rbxlx"
game_status_path = "ReplicatedStorage/GameStatus.luau"
objects_path = "objects/%s"
out_path = "out"
project = "%s.project.json"
sourcemap = "sourcemap.json"
src_path = "src/%s"
