local module = require(script.Parent[".pesde"]["avafe+profileservice"]["1.0.0"]["profileservice"]["ProfileService"])
export type ActiveSession  = module.ActiveSession
export type Listener  = module.Listener 
export type ProfileService  = module.ProfileService 
export type ProfileStore<Data, MetaTags, RobloxMetaData> = module.ProfileStore<Data, MetaTags, RobloxMetaData>
export type GlobalUpdates  = module.GlobalUpdates 
export type Profile<Data, MetaTags, RobloxMetaData> = module.Profile<Data, MetaTags, RobloxMetaData>
return module