local module = require("./.pesde/jiwonz+pathfs/0.6.0-rc.7/pathfs/src/lib/init")
export type Directory  = module.Directory 
export type File  = module.File 
export type Metadata  = module.Metadata 
export type MetadataKind  = module.MetadataKind 
export type MetadataPermissions  = module.MetadataPermissions 
export type WriteOptions  = module.WriteOptions 
export type Components  = module.Components 
export type Path  = module.Path 
export type AsPath  = module.AsPath 
export type Component  = module.Component 
export type DirEntry  = module.DirEntry 
return module