local assets = {
	animations = {
		sleeping = "rbxassetid://112712012552845",
		test = "rbxassetid://80047391560492",
	},
	images = {
		FoodChaos = "rbxassetid://85079220510783",
		TestingAsphalt = "rbxassetid://94940995327129",
	},
	sounds = {
		Events = {
			Race = {
				Freeze = "rbxassetid://15749927835",
				HitSpike = "rbxassetid://117959026306402",
				LapCompleted = "rbxassetid://2578840860",
				Powerup = "rbxassetid://2542932452",
				SpeedBoost = "rbxassetid://8208591201",
				Won = "rbxassetid://2542932452",
			},
		},
	},
}

return assets
