local TeleportService = game:GetService("TeleportService")

local ATTEMPT_LIMIT = 5
local RETRY_DELAY = 1
local FLOOD_DELAY = 15

local function SafeTeleport(placeId, players, options)
	local attemptIndex, success, result = 0, nil, nil
	local reservedServer = TeleportService:ReserveServer(placeId)

	repeat
		success, result = pcall(function()
			return TeleportService:TeleportToPrivateServer(placeId, reservedServer, players, "N/A", options)
		end)
		attemptIndex += 1
		if not success then
			task.wait(RETRY_DELAY)
		end
	until success or attemptIndex == ATTEMPT_LIMIT

	if not success then
		warn(result)
	end

	return success, result
end

TeleportService.TeleportInitFailed:Connect(
	function(player, teleportResult, errorMessage, targetPlaceId, teleportOptions)
		if teleportResult == Enum.TeleportResult.Flooded then
			task.wait(FLOOD_DELAY)
		elseif teleportResult == Enum.TeleportResult.Failure then
			task.wait(RETRY_DELAY)
		else
			error(("Invalid teleport [%s]: %s"):format(teleportResult.Name, errorMessage))
		end

		SafeTeleport(targetPlaceId, { player }, teleportOptions)
	end
)
return SafeTeleport
